server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    url: jdbc:mysql://39.107.61.176:3306/mCloudSql?useSSL=false&serverTimezone=UTC
    username: root
    password: password